#if 0 /* { */
#elif defined(__aarch64__) /* } { */
#define SYS_io_setup 0
#define SYS_io_destroy 1
#define SYS_io_submit 2
#define SYS_io_cancel 3
#define SYS_io_getevents 4
#define SYS_setxattr 5
#define SYS_lsetxattr 6
#define SYS_fsetxattr 7
#define SYS_getxattr 8
#define SYS_lgetxattr 9
#define SYS_fgetxattr 10
#define SYS_listxattr 11
#define SYS_llistxattr 12
#define SYS_flistxattr 13
#define SYS_removexattr 14
#define SYS_lremovexattr 15
#define SYS_fremovexattr 16
#define SYS_getcwd 17
#define SYS_lookup_dcookie 18
#define SYS_eventfd2 19
#define SYS_epoll_create1 20
#define SYS_epoll_ctl 21
#define SYS_epoll_pwait 22
#define SYS_dup 23
#define SYS_dup3 24
#define SYS_fcntl 25
#define SYS_inotify_init1 26
#define SYS_inotify_add_watch 27
#define SYS_inotify_rm_watch 28
#define SYS_ioctl 29
#define SYS_ioprio_set 30
#define SYS_ioprio_get 31
#define SYS_flock 32
#define SYS_mknodat 33
#define SYS_mkdirat 34
#define SYS_unlinkat 35
#define SYS_symlinkat 36
#define SYS_linkat 37
#define SYS_renameat 38
#define SYS_umount2 39
#define SYS_mount 40
#define SYS_pivot_root 41
#define SYS_nfsservctl 42
#define SYS_statfs 43
#define SYS_fstatfs 44
#define SYS_truncate 45
#define SYS_ftruncate 46
#define SYS_fallocate 47
#define SYS_faccessat 48
#define SYS_chdir 49
#define SYS_fchdir 50
#define SYS_chroot 51
#define SYS_fchmod 52
#define SYS_fchmodat 53
#define SYS_fchownat 54
#define SYS_fchown 55
#define SYS_openat 56
#define SYS_close 57
#define SYS_vhangup 58
#define SYS_pipe2 59
#define SYS_quotactl 60
#define SYS_getdents64 61
#define SYS_lseek 62
#define SYS_read 63
#define SYS_write 64
#define SYS_readv 65
#define SYS_writev 66
#define SYS_pread64 67
#define SYS_pwrite64 68
#define SYS_preadv 69
#define SYS_pwritev 70
#define SYS_sendfile 71
#define SYS_pselect6 72
#define SYS_ppoll 73
#define SYS_signalfd4 74
#define SYS_vmsplice 75
#define SYS_splice 76
#define SYS_tee 77
#define SYS_readlinkat 78
#define SYS_newfstatat 79
#define SYS_fstat 80
#define SYS_sync 81
#define SYS_fsync 82
#define SYS_fdatasync 83
#define SYS_sync_file_range 84
#define SYS_timerfd_create 85
#define SYS_timerfd_settime 86
#define SYS_timerfd_gettime 87
#define SYS_utimensat 88
#define SYS_acct 89
#define SYS_capget 90
#define SYS_capset 91
#define SYS_personality 92
#define SYS_exit 93
#define SYS_exit_group 94
#define SYS_waitid 95
#define SYS_set_tid_address 96
#define SYS_unshare 97
#define SYS_futex 98
#define SYS_set_robust_list 99
#define SYS_get_robust_list 100
#define SYS_nanosleep 101
#define SYS_getitimer 102
#define SYS_setitimer 103
#define SYS_kexec_load 104
#define SYS_init_module 105
#define SYS_delete_module 106
#define SYS_timer_create 107
#define SYS_timer_gettime 108
#define SYS_timer_getoverrun 109
#define SYS_timer_settime 110
#define SYS_timer_delete 111
#define SYS_clock_settime 112
#define SYS_clock_gettime 113
#define SYS_clock_getres 114
#define SYS_clock_nanosleep 115
#define SYS_syslog 116
#define SYS_ptrace 117
#define SYS_sched_setparam 118
#define SYS_sched_setscheduler 119
#define SYS_sched_getscheduler 120
#define SYS_sched_getparam 121
#define SYS_sched_setaffinity 122
#define SYS_sched_getaffinity 123
#define SYS_sched_yield 124
#define SYS_sched_get_priority_max 125
#define SYS_sched_get_priority_min 126
#define SYS_sched_rr_get_interval 127
#define SYS_restart_syscall 128
#define SYS_kill 129
#define SYS_tkill 130
#define SYS_tgkill 131
#define SYS_sigaltstack 132
#define SYS_rt_sigsuspend 133
#define SYS_rt_sigaction 134
#define SYS_rt_sigprocmask 135
#define SYS_rt_sigpending 136
#define SYS_rt_sigtimedwait 137
#define SYS_rt_sigqueueinfo 138
#define SYS_rt_sigreturn 139
#define SYS_setpriority 140
#define SYS_getpriority 141
#define SYS_reboot 142
#define SYS_setregid 143
#define SYS_setgid 144
#define SYS_setreuid 145
#define SYS_setuid 146
#define SYS_setresuid 147
#define SYS_getresuid 148
#define SYS_setresgid 149
#define SYS_getresgid 150
#define SYS_setfsuid 151
#define SYS_setfsgid 152
#define SYS_times 153
#define SYS_setpgid 154
#define SYS_getpgid 155
#define SYS_getsid 156
#define SYS_setsid 157
#define SYS_getgroups 158
#define SYS_setgroups 159
#define SYS_uname 160
#define SYS_sethostname 161
#define SYS_setdomainname 162
#define SYS_getrlimit 163
#define SYS_setrlimit 164
#define SYS_getrusage 165
#define SYS_umask 166
#define SYS_prctl 167
#define SYS_getcpu 168
#define SYS_gettimeofday 169
#define SYS_settimeofday 170
#define SYS_adjtimex 171
#define SYS_getpid 172
#define SYS_getppid 173
#define SYS_getuid 174
#define SYS_geteuid 175
#define SYS_getgid 176
#define SYS_getegid 177
#define SYS_gettid 178
#define SYS_sysinfo 179
#define SYS_mq_open 180
#define SYS_mq_unlink 181
#define SYS_mq_timedsend 182
#define SYS_mq_timedreceive 183
#define SYS_mq_notify 184
#define SYS_mq_getsetattr 185
#define SYS_msgget 186
#define SYS_msgctl 187
#define SYS_msgrcv 188
#define SYS_msgsnd 189
#define SYS_semget 190
#define SYS_semctl 191
#define SYS_semtimedop 192
#define SYS_semop 193
#define SYS_shmget 194
#define SYS_shmctl 195
#define SYS_shmat 196
#define SYS_shmdt 197
#define SYS_socket 198
#define SYS_socketpair 199
#define SYS_bind 200
#define SYS_listen 201
#define SYS_accept 202
#define SYS_connect 203
#define SYS_getsockname 204
#define SYS_getpeername 205
#define SYS_sendto 206
#define SYS_recvfrom 207
#define SYS_setsockopt 208
#define SYS_getsockopt 209
#define SYS_shutdown 210
#define SYS_sendmsg 211
#define SYS_recvmsg 212
#define SYS_readahead 213
#define SYS_brk 214
#define SYS_munmap 215
#define SYS_mremap 216
#define SYS_add_key 217
#define SYS_request_key 218
#define SYS_keyctl 219
#define SYS_clone 220
#define SYS_execve 221
#define SYS_mmap 222
#define SYS_fadvise64 223
#define SYS_swapon 224
#define SYS_swapoff 225
#define SYS_mprotect 226
#define SYS_msync 227
#define SYS_mlock 228
#define SYS_munlock 229
#define SYS_mlockall 230
#define SYS_munlockall 231
#define SYS_mincore 232
#define SYS_madvise 233
#define SYS_remap_file_pages 234
#define SYS_mbind 235
#define SYS_get_mempolicy 236
#define SYS_set_mempolicy 237
#define SYS_migrate_pages 238
#define SYS_move_pages 239
#define SYS_rt_tgsigqueueinfo 240
#define SYS_perf_event_open 241
#define SYS_accept4 242
#define SYS_recvmmsg 243
#define SYS_wait4 260
#define SYS_prlimit64 261
#define SYS_fanotify_init 262
#define SYS_fanotify_mark 263
#define SYS_name_to_handle_at 264
#define SYS_open_by_handle_at 265
#define SYS_clock_adjtime 266
#define SYS_syncfs 267
#define SYS_setns 268
#define SYS_sendmmsg 269
#define SYS_process_vm_readv 270
#define SYS_process_vm_writev 271
#define SYS_kcmp 272
#define SYS_finit_module 273
#define SYS_sched_setattr 274
#define SYS_sched_getattr 275
#define SYS_renameat2 276
#define SYS_seccomp 277
#define SYS_getrandom 278
#define SYS_memfd_create 279
#define SYS_bpf 280
#define SYS_execveat 281
#define SYS_userfaultfd 282
#define SYS_membarrier 283
#define SYS_mlock2 284
#define SYS_copy_file_range 285
#define SYS_preadv2 286
#define SYS_pwritev2 287
#define SYS_pkey_mprotect 288
#define SYS_pkey_alloc 289
#define SYS_pkey_free 290
#define SYS_statx 291
#define SYS_io_pgetevents 292
#define SYS_rseq 293
#define SYS_kexec_file_load 294
#define SYS_pidfd_send_signal 424
#define SYS_io_uring_setup 425
#define SYS_io_uring_enter 426
#define SYS_io_uring_register 427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#elif defined(__arm__) /* } { */
#define SYS_restart_syscall	0
#define SYS_exit	1
#define SYS_fork	2
#define SYS_read	3
#define SYS_write	4
#define SYS_open	5
#define SYS_close	6
#define SYS_creat	8
#define SYS_link	9
#define SYS_unlink	10
#define SYS_execve	11
#define SYS_chdir	12
#define SYS_mknod	14
#define SYS_chmod	15
#define SYS_lchown	16
#define SYS_lseek	19
#define SYS_getpid	20
#define SYS_mount	21
#define SYS_setuid	23
#define SYS_getuid	24
#define SYS_ptrace	26
#define SYS_pause	29
#define SYS_access	33
#define SYS_nice	34
#define SYS_sync	36
#define SYS_kill	37
#define SYS_rename	38
#define SYS_mkdir	39
#define SYS_rmdir	40
#define SYS_dup	41
#define SYS_pipe	42
#define SYS_times	43
#define SYS_brk	45
#define SYS_setgid	46
#define SYS_getgid	47
#define SYS_geteuid	49
#define SYS_getegid	50
#define SYS_acct	51
#define SYS_umount2	52
#define SYS_ioctl	54
#define SYS_fcntl	55
#define SYS_setpgid	57
#define SYS_umask	60
#define SYS_chroot	61
#define SYS_ustat	62
#define SYS_dup2	63
#define SYS_getppid	64
#define SYS_getpgrp	65
#define SYS_setsid	66
#define SYS_sigaction	67
#define SYS_setreuid	70
#define SYS_setregid	71
#define SYS_sigsuspend	72
#define SYS_sigpending	73
#define SYS_sethostname	74
#define SYS_setrlimit	75
#define SYS_getrusage	77
#define SYS_gettimeofday_time32	78
#define SYS_settimeofday_time32	79
#define SYS_getgroups	80
#define SYS_setgroups	81
#define SYS_symlink	83
#define SYS_readlink	85
#define SYS_uselib	86
#define SYS_swapon	87
#define SYS_reboot	88
#define SYS_munmap	91
#define SYS_truncate	92
#define SYS_ftruncate	93
#define SYS_fchmod	94
#define SYS_fchown	95
#define SYS_getpriority	96
#define SYS_setpriority	97
#define SYS_statfs	99
#define SYS_fstatfs	100
#define SYS_syslog	103
#define SYS_setitimer	104
#define SYS_getitimer	105
#define SYS_stat	106
#define SYS_lstat	107
#define SYS_fstat	108
#define SYS_vhangup	111
#define SYS_wait4	114
#define SYS_swapoff	115
#define SYS_sysinfo	116
#define SYS_fsync	118
#define SYS_sigreturn	119
#define SYS_clone	120
#define SYS_setdomainname	121
#define SYS_uname	122
#define SYS_adjtimex	124
#define SYS_mprotect	125
#define SYS_sigprocmask	126
#define SYS_init_module	128
#define SYS_delete_module	129
#define SYS_quotactl	131
#define SYS_getpgid	132
#define SYS_fchdir	133
#define SYS_bdflush	134
#define SYS_sysfs	135
#define SYS_personality	136
#define SYS_setfsuid	138
#define SYS_setfsgid	139
#define SYS__llseek	140
#define SYS_getdents	141
#define SYS__newselect	142
#define SYS_flock	143
#define SYS_msync	144
#define SYS_readv	145
#define SYS_writev	146
#define SYS_getsid	147
#define SYS_fdatasync	148
#define SYS__sysctl	149
#define SYS_mlock	150
#define SYS_munlock	151
#define SYS_mlockall	152
#define SYS_munlockall	153
#define SYS_sched_setparam	154
#define SYS_sched_getparam	155
#define SYS_sched_setscheduler	156
#define SYS_sched_getscheduler	157
#define SYS_sched_yield	158
#define SYS_sched_get_priority_max	159
#define SYS_sched_get_priority_min	160
#define SYS_sched_rr_get_interval	161
#define SYS_nanosleep	162
#define SYS_mremap	163
#define SYS_setresuid	164
#define SYS_getresuid	165
#define SYS_poll	168
#define SYS_nfsservctl	169
#define SYS_setresgid	170
#define SYS_getresgid	171
#define SYS_prctl	172
#define SYS_rt_sigreturn	173
#define SYS_rt_sigaction	174
#define SYS_rt_sigprocmask	175
#define SYS_rt_sigpending	176
#define SYS_rt_sigtimedwait	177
#define SYS_rt_sigqueueinfo	178
#define SYS_rt_sigsuspend	179
#define SYS_pread64	180
#define SYS_pwrite64	181
#define SYS_chown	182
#define SYS_getcwd	183
#define SYS_capget	184
#define SYS_capset	185
#define SYS_sigaltstack	186
#define SYS_sendfile	187
#define SYS_vfork	190
#define SYS_ugetrlimit	191
#define SYS_mmap2	192
#define SYS_truncate64	193
#define SYS_ftruncate64	194
#define SYS_stat64	195
#define SYS_lstat64	196
#define SYS_fstat64	197
#define SYS_lchown32	198
#define SYS_getuid32	199
#define SYS_getgid32	200
#define SYS_geteuid32	201
#define SYS_getegid32	202
#define SYS_setreuid32	203
#define SYS_setregid32	204
#define SYS_getgroups32	205
#define SYS_setgroups32	206
#define SYS_fchown32	207
#define SYS_setresuid32	208
#define SYS_getresuid32	209
#define SYS_setresgid32	210
#define SYS_getresgid32	211
#define SYS_chown32	212
#define SYS_setuid32	213
#define SYS_setgid32	214
#define SYS_setfsuid32	215
#define SYS_setfsgid32	216
#define SYS_getdents64	217
#define SYS_pivot_root	218
#define SYS_mincore	219
#define SYS_madvise	220
#define SYS_fcntl64	221
#define SYS_gettid	224
#define SYS_readahead	225
#define SYS_setxattr	226
#define SYS_lsetxattr	227
#define SYS_fsetxattr	228
#define SYS_getxattr	229
#define SYS_lgetxattr	230
#define SYS_fgetxattr	231
#define SYS_listxattr	232
#define SYS_llistxattr	233
#define SYS_flistxattr	234
#define SYS_removexattr	235
#define SYS_lremovexattr	236
#define SYS_fremovexattr	237
#define SYS_tkill	238
#define SYS_sendfile64	239
#define SYS_futex	240
#define SYS_sched_setaffinity	241
#define SYS_sched_getaffinity	242
#define SYS_io_setup	243
#define SYS_io_destroy	244
#define SYS_io_getevents	245
#define SYS_io_submit	246
#define SYS_io_cancel	247
#define SYS_exit_group	248
#define SYS_lookup_dcookie	249
#define SYS_epoll_create	250
#define SYS_epoll_ctl	251
#define SYS_epoll_wait	252
#define SYS_remap_file_pages	253
#define SYS_set_tid_address	256
#define SYS_timer_create	257
#define SYS_timer_settime32	258
#define SYS_timer_gettime32	259
#define SYS_timer_getoverrun	260
#define SYS_timer_delete	261
#define SYS_clock_settime32	262
#define SYS_clock_gettime32	263
#define SYS_clock_getres_time32	264
#define SYS_clock_nanosleep_time32	265
#define SYS_statfs64	266
#define SYS_fstatfs64	267
#define SYS_tgkill	268
#define SYS_utimes	269
#define SYS_fadvise64_64	270
#define SYS_arm_fadvise64_64	270
#define SYS_pciconfig_iobase	271
#define SYS_pciconfig_read	272
#define SYS_pciconfig_write	273
#define SYS_mq_open	274
#define SYS_mq_unlink	275
#define SYS_mq_timedsend	276
#define SYS_mq_timedreceive	277
#define SYS_mq_notify	278
#define SYS_mq_getsetattr	279
#define SYS_waitid	280
#define SYS_socket	281
#define SYS_bind	282
#define SYS_connect	283
#define SYS_listen	284
#define SYS_accept	285
#define SYS_getsockname	286
#define SYS_getpeername	287
#define SYS_socketpair	288
#define SYS_send	289
#define SYS_sendto	290
#define SYS_recv	291
#define SYS_recvfrom	292
#define SYS_shutdown	293
#define SYS_setsockopt	294
#define SYS_getsockopt	295
#define SYS_sendmsg	296
#define SYS_recvmsg	297
#define SYS_semop	298
#define SYS_semget	299
#define SYS_semctl	300
#define SYS_msgsnd	301
#define SYS_msgrcv	302
#define SYS_msgget	303
#define SYS_msgctl	304
#define SYS_shmat	305
#define SYS_shmdt	306
#define SYS_shmget	307
#define SYS_shmctl	308
#define SYS_add_key	309
#define SYS_request_key	310
#define SYS_keyctl	311
#define SYS_semtimedop	312
#define SYS_vserver	313
#define SYS_ioprio_set	314
#define SYS_ioprio_get	315
#define SYS_inotify_init	316
#define SYS_inotify_add_watch	317
#define SYS_inotify_rm_watch	318
#define SYS_mbind	319
#define SYS_get_mempolicy	320
#define SYS_set_mempolicy	321
#define SYS_openat	322
#define SYS_mkdirat	323
#define SYS_mknodat	324
#define SYS_fchownat	325
#define SYS_futimesat	326
#define SYS_fstatat64	327
#define SYS_unlinkat	328
#define SYS_renameat	329
#define SYS_linkat	330
#define SYS_symlinkat	331
#define SYS_readlinkat	332
#define SYS_fchmodat	333
#define SYS_faccessat	334
#define SYS_pselect6	335
#define SYS_ppoll	336
#define SYS_unshare	337
#define SYS_set_robust_list	338
#define SYS_get_robust_list	339
#define SYS_splice	340
#define SYS_sync_file_range2	341
#define SYS_arm_sync_file_range	341
#define SYS_tee	342
#define SYS_vmsplice	343
#define SYS_move_pages	344
#define SYS_getcpu	345
#define SYS_epoll_pwait	346
#define SYS_kexec_load	347
#define SYS_utimensat	348
#define SYS_signalfd	349
#define SYS_timerfd_create	350
#define SYS_eventfd	351
#define SYS_fallocate	352
#define SYS_timerfd_settime32	353
#define SYS_timerfd_gettime32	354
#define SYS_signalfd4	355
#define SYS_eventfd2	356
#define SYS_epoll_create1	357
#define SYS_dup3	358
#define SYS_pipe2	359
#define SYS_inotify_init1	360
#define SYS_preadv	361
#define SYS_pwritev	362
#define SYS_rt_tgsigqueueinfo	363
#define SYS_perf_event_open	364
#define SYS_recvmmsg	365
#define SYS_accept4	366
#define SYS_fanotify_init	367
#define SYS_fanotify_mark	368
#define SYS_prlimit64	369
#define SYS_name_to_handle_at	370
#define SYS_open_by_handle_at	371
#define SYS_clock_adjtime	372
#define SYS_syncfs	373
#define SYS_sendmmsg	374
#define SYS_setns	375
#define SYS_process_vm_readv	376
#define SYS_process_vm_writev	377
#define SYS_kcmp		378
#define SYS_finit_module	379
#define SYS_sched_setattr	380
#define SYS_sched_getattr	381
#define SYS_renameat2	382
#define SYS_seccomp	383
#define SYS_getrandom	384
#define SYS_memfd_create	385
#define SYS_bpf	386
#define SYS_execveat	387
#define SYS_userfaultfd	388
#define SYS_membarrier		389
#define SYS_mlock2		390
#define SYS_copy_file_range	391
#define SYS_preadv2	392
#define SYS_pwritev2	393
#define SYS_pkey_mprotect	394
#define SYS_pkey_alloc	395
#define SYS_pkey_free	396
#define SYS_statx	397
#define SYS_rseq	398
#define SYS_io_pgetevents	399
#define SYS_migrate_pages	400
#define SYS_kexec_file_load	401
#define SYS_clock_gettime64	403
#define SYS_clock_settime64	404
#define SYS_clock_adjtime64	405
#define SYS_clock_getres_time64	406
#define SYS_clock_nanosleep_time64	407
#define SYS_timer_gettime64	408
#define SYS_timer_settime64	409
#define SYS_timerfd_gettime64	410
#define SYS_timerfd_settime64	411
#define SYS_utimensat_time64	412
#define SYS_pselect6_time64	413
#define SYS_ppoll_time64	414
#define SYS_io_pgetevents_time64	416
#define SYS_recvmmsg_time64	417
#define SYS_mq_timedsend_time64	418
#define SYS_mq_timedreceive_time64	419
#define SYS_semtimedop_time64	420
#define SYS_rt_sigtimedwait_time64	421
#define SYS_futex_time64	422
#define SYS_sched_rr_get_interval_time64	423
#define SYS_pidfd_send_signal	424
#define SYS_io_uring_setup	425
#define SYS_io_uring_enter	426
#define SYS_io_uring_register	427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#define __ARM_NR_breakpoint	0x0f0001
#define __ARM_NR_cacheflush	0x0f0002
#define __ARM_NR_usr26		0x0f0003
#define __ARM_NR_usr32		0x0f0004
#define __ARM_NR_set_tls	0x0f0005
#define __ARM_NR_get_tls	0x0f0006

#elif defined(__i386__) /* } { */
#define SYS_restart_syscall      0
#define SYS_exit		  1
#define SYS_fork		  2
#define SYS_read		  3
#define SYS_write		  4
#define SYS_open		  5
#define SYS_close		  6
#define SYS_waitpid		  7
#define SYS_creat		  8
#define SYS_link		  9
#define SYS_unlink		 10
#define SYS_execve		 11
#define SYS_chdir		 12
#define SYS_time		 13
#define SYS_mknod		 14
#define SYS_chmod		 15
#define SYS_lchown		 16
#define SYS_break		 17
#define SYS_oldstat		 18
#define SYS_lseek		 19
#define SYS_getpid		 20
#define SYS_mount		 21
#define SYS_umount		 22
#define SYS_setuid		 23
#define SYS_getuid		 24
#define SYS_stime		 25
#define SYS_ptrace		 26
#define SYS_alarm		 27
#define SYS_oldfstat		 28
#define SYS_pause		 29
#define SYS_utime		 30
#define SYS_stty		 31
#define SYS_gtty		 32
#define SYS_access		 33
#define SYS_nice		 34
#define SYS_ftime		 35
#define SYS_sync		 36
#define SYS_kill		 37
#define SYS_rename		 38
#define SYS_mkdir		 39
#define SYS_rmdir		 40
#define SYS_dup		 41
#define SYS_pipe		 42
#define SYS_times		 43
#define SYS_prof		 44
#define SYS_brk		 45
#define SYS_setgid		 46
#define SYS_getgid		 47
#define SYS_signal		 48
#define SYS_geteuid		 49
#define SYS_getegid		 50
#define SYS_acct		 51
#define SYS_umount2		 52
#define SYS_lock		 53
#define SYS_ioctl		 54
#define SYS_fcntl		 55
#define SYS_mpx		 56
#define SYS_setpgid		 57
#define SYS_ulimit		 58
#define SYS_oldolduname	 59
#define SYS_umask		 60
#define SYS_chroot		 61
#define SYS_ustat		 62
#define SYS_dup2		 63
#define SYS_getppid		 64
#define SYS_getpgrp		 65
#define SYS_setsid		 66
#define SYS_sigaction		 67
#define SYS_sgetmask		 68
#define SYS_ssetmask		 69
#define SYS_setreuid		 70
#define SYS_setregid		 71
#define SYS_sigsuspend		 72
#define SYS_sigpending		 73
#define SYS_sethostname	 74
#define SYS_setrlimit		 75
#define SYS_getrlimit		 76   /* Back compatible 2Gig limited rlimit */
#define SYS_getrusage		 77
#define SYS_gettimeofday_time32	 78
#define SYS_settimeofday_time32	 79
#define SYS_getgroups		 80
#define SYS_setgroups		 81
#define SYS_select		 82
#define SYS_symlink		 83
#define SYS_oldlstat		 84
#define SYS_readlink		 85
#define SYS_uselib		 86
#define SYS_swapon		 87
#define SYS_reboot		 88
#define SYS_readdir		 89
#define SYS_mmap		 90
#define SYS_munmap		 91
#define SYS_truncate		 92
#define SYS_ftruncate		 93
#define SYS_fchmod		 94
#define SYS_fchown		 95
#define SYS_getpriority	 96
#define SYS_setpriority	 97
#define SYS_profil		 98
#define SYS_statfs		99
#define SYS_fstatfs		100
#define SYS_ioperm		101
#define SYS_socketcall		102
#define SYS_syslog		103
#define SYS_setitimer		104
#define SYS_getitimer		105
#define SYS_stat		106
#define SYS_lstat		107
#define SYS_fstat		108
#define SYS_olduname		109
#define SYS_iopl		110
#define SYS_vhangup		111
#define SYS_idle		112
#define SYS_vm86old		113
#define SYS_wait4		114
#define SYS_swapoff		115
#define SYS_sysinfo		116
#define SYS_ipc		117
#define SYS_fsync		118
#define SYS_sigreturn		119
#define SYS_clone		120
#define SYS_setdomainname	121
#define SYS_uname		122
#define SYS_modify_ldt		123
#define SYS_adjtimex		124
#define SYS_mprotect		125
#define SYS_sigprocmask	126
#define SYS_create_module	127
#define SYS_init_module	128
#define SYS_delete_module	129
#define SYS_get_kernel_syms	130
#define SYS_quotactl		131
#define SYS_getpgid		132
#define SYS_fchdir		133
#define SYS_bdflush		134
#define SYS_sysfs		135
#define SYS_personality	136
#define SYS_afs_syscall	137
#define SYS_setfsuid		138
#define SYS_setfsgid		139
#define SYS__llseek		140
#define SYS_getdents		141
#define SYS__newselect		142
#define SYS_flock		143
#define SYS_msync		144
#define SYS_readv		145
#define SYS_writev		146
#define SYS_getsid		147
#define SYS_fdatasync		148
#define SYS__sysctl		149
#define SYS_mlock		150
#define SYS_munlock		151
#define SYS_mlockall		152
#define SYS_munlockall		153
#define SYS_sched_setparam		154
#define SYS_sched_getparam		155
#define SYS_sched_setscheduler		156
#define SYS_sched_getscheduler		157
#define SYS_sched_yield		158
#define SYS_sched_get_priority_max	159
#define SYS_sched_get_priority_min	160
#define SYS_sched_rr_get_interval	161
#define SYS_nanosleep		162
#define SYS_mremap		163
#define SYS_setresuid		164
#define SYS_getresuid		165
#define SYS_vm86		166
#define SYS_query_module	167
#define SYS_poll		168
#define SYS_nfsservctl		169
#define SYS_setresgid		170
#define SYS_getresgid		171
#define SYS_prctl              172
#define SYS_rt_sigreturn	173
#define SYS_rt_sigaction	174
#define SYS_rt_sigprocmask	175
#define SYS_rt_sigpending	176
#define SYS_rt_sigtimedwait	177
#define SYS_rt_sigqueueinfo	178
#define SYS_rt_sigsuspend	179
#define SYS_pread64		180
#define SYS_pwrite64		181
#define SYS_chown		182
#define SYS_getcwd		183
#define SYS_capget		184
#define SYS_capset		185
#define SYS_sigaltstack	186
#define SYS_sendfile		187
#define SYS_getpmsg		188
#define SYS_putpmsg		189
#define SYS_vfork		190
#define SYS_ugetrlimit		191
#define SYS_mmap2		192
#define SYS_truncate64		193
#define SYS_ftruncate64	194
#define SYS_stat64		195
#define SYS_lstat64		196
#define SYS_fstat64		197
#define SYS_lchown32		198
#define SYS_getuid32		199
#define SYS_getgid32		200
#define SYS_geteuid32		201
#define SYS_getegid32		202
#define SYS_setreuid32		203
#define SYS_setregid32		204
#define SYS_getgroups32	205
#define SYS_setgroups32	206
#define SYS_fchown32		207
#define SYS_setresuid32	208
#define SYS_getresuid32	209
#define SYS_setresgid32	210
#define SYS_getresgid32	211
#define SYS_chown32		212
#define SYS_setuid32		213
#define SYS_setgid32		214
#define SYS_setfsuid32		215
#define SYS_setfsgid32		216
#define SYS_pivot_root		217
#define SYS_mincore		218
#define SYS_madvise		219
#define SYS_getdents64		220
#define SYS_fcntl64		221
/* 223 is unused */
#define SYS_gettid		224
#define SYS_readahead		225
#define SYS_setxattr		226
#define SYS_lsetxattr		227
#define SYS_fsetxattr		228
#define SYS_getxattr		229
#define SYS_lgetxattr		230
#define SYS_fgetxattr		231
#define SYS_listxattr		232
#define SYS_llistxattr		233
#define SYS_flistxattr		234
#define SYS_removexattr	235
#define SYS_lremovexattr	236
#define SYS_fremovexattr	237
#define SYS_tkill		238
#define SYS_sendfile64		239
#define SYS_futex		240
#define SYS_sched_setaffinity	241
#define SYS_sched_getaffinity	242
#define SYS_set_thread_area	243
#define SYS_get_thread_area	244
#define SYS_io_setup		245
#define SYS_io_destroy		246
#define SYS_io_getevents	247
#define SYS_io_submit		248
#define SYS_io_cancel		249
#define SYS_fadvise64		250
/* 251 is available for reuse (was briefly sys_set_zone_reclaim) */
#define SYS_exit_group		252
#define SYS_lookup_dcookie	253
#define SYS_epoll_create	254
#define SYS_epoll_ctl		255
#define SYS_epoll_wait		256
#define SYS_remap_file_pages	257
#define SYS_set_tid_address	258
#define SYS_timer_create	259
#define SYS_timer_settime32	(SYS_timer_create+1)
#define SYS_timer_gettime32	(SYS_timer_create+2)
#define SYS_timer_getoverrun	(SYS_timer_create+3)
#define SYS_timer_delete	(SYS_timer_create+4)
#define SYS_clock_settime32	(SYS_timer_create+5)
#define SYS_clock_gettime32	(SYS_timer_create+6)
#define SYS_clock_getres_time32	(SYS_timer_create+7)
#define SYS_clock_nanosleep_time32	(SYS_timer_create+8)
#define SYS_statfs64		268
#define SYS_fstatfs64		269
#define SYS_tgkill		270
#define SYS_utimes		271
#define SYS_fadvise64_64	272
#define SYS_vserver		273
#define SYS_mbind		274
#define SYS_get_mempolicy	275
#define SYS_set_mempolicy	276
#define SYS_mq_open 		277
#define SYS_mq_unlink		(SYS_mq_open+1)
#define SYS_mq_timedsend	(SYS_mq_open+2)
#define SYS_mq_timedreceive	(SYS_mq_open+3)
#define SYS_mq_notify		(SYS_mq_open+4)
#define SYS_mq_getsetattr	(SYS_mq_open+5)
#define SYS_kexec_load		283
#define SYS_waitid		284
/* #define SYS_sys_setaltroot	285 */
#define SYS_add_key		286
#define SYS_request_key	287
#define SYS_keyctl		288
#define SYS_ioprio_set		289
#define SYS_ioprio_get		290
#define SYS_inotify_init	291
#define SYS_inotify_add_watch	292
#define SYS_inotify_rm_watch	293
#define SYS_migrate_pages	294
#define SYS_openat		295
#define SYS_mkdirat		296
#define SYS_mknodat		297
#define SYS_fchownat		298
#define SYS_futimesat		299
#define SYS_fstatat64		300
#define SYS_unlinkat		301
#define SYS_renameat		302
#define SYS_linkat		303
#define SYS_symlinkat		304
#define SYS_readlinkat		305
#define SYS_fchmodat		306
#define SYS_faccessat		307
#define SYS_pselect6		308
#define SYS_ppoll		309
#define SYS_unshare		310
#define SYS_set_robust_list	311
#define SYS_get_robust_list	312
#define SYS_splice		313
#define SYS_sync_file_range	314
#define SYS_tee		315
#define SYS_vmsplice		316
#define SYS_move_pages		317
#define SYS_getcpu		318
#define SYS_epoll_pwait	319
#define SYS_utimensat		320
#define SYS_signalfd		321
#define SYS_timerfd_create	322
#define SYS_eventfd		323
#define SYS_fallocate		324
#define SYS_timerfd_settime32	325
#define SYS_timerfd_gettime32	326
#define SYS_signalfd4		327
#define SYS_eventfd2		328
#define SYS_epoll_create1	329
#define SYS_dup3		330
#define SYS_pipe2		331
#define SYS_inotify_init1	332
#define SYS_preadv		333
#define SYS_pwritev		334
#define SYS_rt_tgsigqueueinfo	335
#define SYS_perf_event_open	336
#define SYS_recvmmsg		337
#define SYS_fanotify_init	338
#define SYS_fanotify_mark	339
#define SYS_prlimit64		340
#define SYS_name_to_handle_at	341
#define SYS_open_by_handle_at	342
#define SYS_clock_adjtime	343
#define SYS_syncfs		344
#define SYS_sendmmsg		345
#define SYS_setns		346
#define SYS_process_vm_readv	347
#define SYS_process_vm_writev	348
#define SYS_kcmp		349
#define SYS_finit_module	350
#define SYS_sched_setattr	351
#define SYS_sched_getattr	352
#define SYS_renameat2		353
#define SYS_seccomp		354
#define SYS_getrandom		355
#define SYS_memfd_create	356
#define SYS_bpf		357
#define SYS_execveat		358
#define SYS_socket		359
#define SYS_socketpair		360
#define SYS_bind		361
#define SYS_connect		362
#define SYS_listen		363
#define SYS_accept4		364
#define SYS_getsockopt		365
#define SYS_setsockopt		366
#define SYS_getsockname	367
#define SYS_getpeername	368
#define SYS_sendto		369
#define SYS_sendmsg		370
#define SYS_recvfrom		371
#define SYS_recvmsg		372
#define SYS_shutdown		373
#define SYS_userfaultfd	374
#define SYS_membarrier		375
#define SYS_mlock2		376
#define SYS_copy_file_range	377
#define SYS_preadv2		378
#define SYS_pwritev2		379
#define SYS_pkey_mprotect	380
#define SYS_pkey_alloc		381
#define SYS_pkey_free		382
#define SYS_statx		383
#define SYS_arch_prctl		384
#define SYS_io_pgetevents	385
#define SYS_rseq		386
#define SYS_semget		393
#define SYS_semctl		394
#define SYS_shmget		395
#define SYS_shmctl		396
#define SYS_shmat		397
#define SYS_shmdt		398
#define SYS_msgget		399
#define SYS_msgsnd		400
#define SYS_msgrcv		401
#define SYS_msgctl		402
#define SYS_clock_gettime64	403
#define SYS_clock_settime64	404
#define SYS_clock_adjtime64	405
#define SYS_clock_getres_time64 406
#define SYS_clock_nanosleep_time64 407
#define SYS_timer_gettime64	408
#define SYS_timer_settime64	409
#define SYS_timerfd_gettime64	410
#define SYS_timerfd_settime64	411
#define SYS_utimensat_time64	412
#define SYS_pselect6_time64	413
#define SYS_ppoll_time64	414
#define SYS_io_pgetevents_time64 416
#define SYS_recvmmsg_time64	417
#define SYS_mq_timedsend_time64 418
#define SYS_mq_timedreceive_time64 419
#define SYS_semtimedop_time64	420
#define SYS_rt_sigtimedwait_time64 421
#define SYS_futex_time64	422
#define SYS_sched_rr_get_interval_time64 423
#define SYS_pidfd_send_signal	424
#define SYS_io_uring_setup	425
#define SYS_io_uring_enter	426
#define SYS_io_uring_register	427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_memfd_secret	447
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#elif defined(__powerpc__) && !defined(__powerpc64__) /* } { */
#define SYS_restart_syscall          0
#define SYS_exit                     1
#define SYS_fork                     2
#define SYS_read                     3
#define SYS_write                    4
#define SYS_open                     5
#define SYS_close                    6
#define SYS_waitpid                  7
#define SYS_creat                    8
#define SYS_link                     9
#define SYS_unlink                  10
#define SYS_execve                  11
#define SYS_chdir                   12
#define SYS_time                    13
#define SYS_mknod                   14
#define SYS_chmod                   15
#define SYS_lchown                  16
#define SYS_break                   17
#define SYS_oldstat                 18
#define SYS_lseek                   19
#define SYS_getpid                  20
#define SYS_mount                   21
#define SYS_umount                  22
#define SYS_setuid                  23
#define SYS_getuid                  24
#define SYS_stime                   25
#define SYS_ptrace                  26
#define SYS_alarm                   27
#define SYS_oldfstat                28
#define SYS_pause                   29
#define SYS_utime                   30
#define SYS_stty                    31
#define SYS_gtty                    32
#define SYS_access                  33
#define SYS_nice                    34
#define SYS_ftime                   35
#define SYS_sync                    36
#define SYS_kill                    37
#define SYS_rename                  38
#define SYS_mkdir                   39
#define SYS_rmdir                   40
#define SYS_dup                     41
#define SYS_pipe                    42
#define SYS_times                   43
#define SYS_prof                    44
#define SYS_brk                     45
#define SYS_setgid                  46
#define SYS_getgid                  47
#define SYS_signal                  48
#define SYS_geteuid                 49
#define SYS_getegid                 50
#define SYS_acct                    51
#define SYS_umount2                 52
#define SYS_lock                    53
#define SYS_ioctl                   54
#define SYS_fcntl                   55
#define SYS_mpx                     56
#define SYS_setpgid                 57
#define SYS_ulimit                  58
#define SYS_oldolduname             59
#define SYS_umask                   60
#define SYS_chroot                  61
#define SYS_ustat                   62
#define SYS_dup2                    63
#define SYS_getppid                 64
#define SYS_getpgrp                 65
#define SYS_setsid                  66
#define SYS_sigaction               67
#define SYS_sgetmask                68
#define SYS_ssetmask                69
#define SYS_setreuid                70
#define SYS_setregid                71
#define SYS_sigsuspend              72
#define SYS_sigpending              73
#define SYS_sethostname             74
#define SYS_setrlimit               75
#define SYS_getrlimit               76
#define SYS_getrusage               77
#define SYS_gettimeofday_time32            78
#define SYS_settimeofday_time32            79
#define SYS_getgroups               80
#define SYS_setgroups               81
#define SYS_select                  82
#define SYS_symlink                 83
#define SYS_oldlstat                84
#define SYS_readlink                85
#define SYS_uselib                  86
#define SYS_swapon                  87
#define SYS_reboot                  88
#define SYS_readdir                 89
#define SYS_mmap                    90
#define SYS_munmap                  91
#define SYS_truncate                92
#define SYS_ftruncate               93
#define SYS_fchmod                  94
#define SYS_fchown                  95
#define SYS_getpriority             96
#define SYS_setpriority             97
#define SYS_profil                  98
#define SYS_statfs                  99
#define SYS_fstatfs                100
#define SYS_ioperm                 101
#define SYS_socketcall             102
#define SYS_syslog                 103
#define SYS_setitimer              104
#define SYS_getitimer              105
#define SYS_stat                   106
#define SYS_lstat                  107
#define SYS_fstat                  108
#define SYS_olduname               109
#define SYS_iopl                   110
#define SYS_vhangup                111
#define SYS_idle                   112
#define SYS_vm86                   113
#define SYS_wait4                  114
#define SYS_swapoff                115
#define SYS_sysinfo                116
#define SYS_ipc                    117
#define SYS_fsync                  118
#define SYS_sigreturn              119
#define SYS_clone                  120
#define SYS_setdomainname          121
#define SYS_uname                  122
#define SYS_modify_ldt             123
#define SYS_adjtimex               124
#define SYS_mprotect               125
#define SYS_sigprocmask            126
#define SYS_create_module          127
#define SYS_init_module            128
#define SYS_delete_module          129
#define SYS_get_kernel_syms        130
#define SYS_quotactl               131
#define SYS_getpgid                132
#define SYS_fchdir                 133
#define SYS_bdflush                134
#define SYS_sysfs                  135
#define SYS_personality            136
#define SYS_afs_syscall            137
#define SYS_setfsuid               138
#define SYS_setfsgid               139
#define SYS__llseek                140
#define SYS_getdents               141
#define SYS__newselect             142
#define SYS_flock                  143
#define SYS_msync                  144
#define SYS_readv                  145
#define SYS_writev                 146
#define SYS_getsid                 147
#define SYS_fdatasync              148
#define SYS__sysctl                149
#define SYS_mlock                  150
#define SYS_munlock                151
#define SYS_mlockall               152
#define SYS_munlockall             153
#define SYS_sched_setparam         154
#define SYS_sched_getparam         155
#define SYS_sched_setscheduler     156
#define SYS_sched_getscheduler     157
#define SYS_sched_yield            158
#define SYS_sched_get_priority_max 159
#define SYS_sched_get_priority_min 160
#define SYS_sched_rr_get_interval  161
#define SYS_nanosleep              162
#define SYS_mremap                 163
#define SYS_setresuid              164
#define SYS_getresuid              165
#define SYS_query_module           166
#define SYS_poll                   167
#define SYS_nfsservctl             168
#define SYS_setresgid              169
#define SYS_getresgid              170
#define SYS_prctl                  171
#define SYS_rt_sigreturn           172
#define SYS_rt_sigaction           173
#define SYS_rt_sigprocmask         174
#define SYS_rt_sigpending          175
#define SYS_rt_sigtimedwait        176
#define SYS_rt_sigqueueinfo        177
#define SYS_rt_sigsuspend          178
#define SYS_pread64                179
#define SYS_pwrite64               180
#define SYS_chown                  181
#define SYS_getcwd                 182
#define SYS_capget                 183
#define SYS_capset                 184
#define SYS_sigaltstack            185
#define SYS_sendfile               186
#define SYS_getpmsg                187
#define SYS_putpmsg                188
#define SYS_vfork                  189
#define SYS_ugetrlimit             190
#define SYS_readahead              191
#define SYS_mmap2                  192
#define SYS_truncate64             193
#define SYS_ftruncate64            194
#define SYS_stat64                 195
#define SYS_lstat64                196
#define SYS_fstat64                197
#define SYS_pciconfig_read         198
#define SYS_pciconfig_write        199
#define SYS_pciconfig_iobase       200
#define SYS_multiplexer            201
#define SYS_getdents64             202
#define SYS_pivot_root             203
#define SYS_fcntl64                204
#define SYS_madvise                205
#define SYS_mincore                206
#define SYS_gettid                 207
#define SYS_tkill                  208
#define SYS_setxattr               209
#define SYS_lsetxattr              210
#define SYS_fsetxattr              211
#define SYS_getxattr               212
#define SYS_lgetxattr              213
#define SYS_fgetxattr              214
#define SYS_listxattr              215
#define SYS_llistxattr             216
#define SYS_flistxattr             217
#define SYS_removexattr            218
#define SYS_lremovexattr           219
#define SYS_fremovexattr           220
#define SYS_futex                  221
#define SYS_sched_setaffinity      222
#define SYS_sched_getaffinity      223
#define SYS_tuxcall                225
#define SYS_sendfile64             226
#define SYS_io_setup               227
#define SYS_io_destroy             228
#define SYS_io_getevents           229
#define SYS_io_submit              230
#define SYS_io_cancel              231
#define SYS_set_tid_address        232
#define SYS_fadvise64              233
#define SYS_exit_group             234
#define SYS_lookup_dcookie         235
#define SYS_epoll_create           236
#define SYS_epoll_ctl              237
#define SYS_epoll_wait             238
#define SYS_remap_file_pages       239
#define SYS_timer_create           240
#define SYS_timer_settime32          241
#define SYS_timer_gettime32          242
#define SYS_timer_getoverrun       243
#define SYS_timer_delete           244
#define SYS_clock_settime32          245
#define SYS_clock_gettime32          246
#define SYS_clock_getres_time32           247
#define SYS_clock_nanosleep_time32        248
#define SYS_swapcontext            249
#define SYS_tgkill                 250
#define SYS_utimes                 251
#define SYS_statfs64               252
#define SYS_fstatfs64              253
#define SYS_fadvise64_64           254
#define SYS_rtas		255
#define SYS_sys_debug_setcontext 256
#define SYS_migrate_pages	258
#define SYS_mbind		259
#define SYS_get_mempolicy	260
#define SYS_set_mempolicy	261
#define SYS_mq_open		262
#define SYS_mq_unlink		263
#define SYS_mq_timedsend	264
#define SYS_mq_timedreceive	265
#define SYS_mq_notify		266
#define SYS_mq_getsetattr	267
#define SYS_kexec_load		268
#define SYS_add_key		269
#define SYS_request_key	270
#define SYS_keyctl		271
#define SYS_waitid		272
#define SYS_ioprio_set		273
#define SYS_ioprio_get		274
#define SYS_inotify_init	275
#define SYS_inotify_add_watch	276
#define SYS_inotify_rm_watch	277
#define SYS_spu_run		278
#define SYS_spu_create		279
#define SYS_pselect6		280
#define SYS_ppoll		281
#define SYS_unshare		282
#define SYS_splice		283
#define SYS_tee		284
#define SYS_vmsplice		285
#define SYS_openat		286
#define SYS_mkdirat		287
#define SYS_mknodat		288
#define SYS_fchownat		289
#define SYS_futimesat		290
#define SYS_fstatat64		291
#define SYS_unlinkat		292
#define SYS_renameat		293
#define SYS_linkat		294
#define SYS_symlinkat		295
#define SYS_readlinkat		296
#define SYS_fchmodat		297
#define SYS_faccessat		298
#define SYS_get_robust_list	299
#define SYS_set_robust_list	300
#define SYS_move_pages		301
#define SYS_getcpu		302
#define SYS_epoll_pwait	303
#define SYS_utimensat		304
#define SYS_signalfd		305
#define SYS_timerfd_create     306
#define SYS_eventfd		307
#define SYS_sync_file_range2	308
#define SYS_fallocate		309
#define SYS_subpage_prot		310
#define SYS_timerfd_settime32	311
#define SYS_timerfd_gettime32	312
#define SYS_signalfd4		313
#define SYS_eventfd2		314
#define SYS_epoll_create1	315
#define SYS_dup3			316
#define SYS_pipe2		317
#define SYS_inotify_init1	318
#define SYS_perf_event_open       319
#define SYS_preadv                320
#define SYS_pwritev               321
#define SYS_rt_tgsigqueueinfo     322
#define SYS_fanotify_init         323
#define SYS_fanotify_mark         324
#define SYS_prlimit64             325
#define SYS_socket                326
#define SYS_bind                  327
#define SYS_connect               328
#define SYS_listen                329
#define SYS_accept                330
#define SYS_getsockname           331
#define SYS_getpeername           332
#define SYS_socketpair            333
#define SYS_send                  334
#define SYS_sendto                335
#define SYS_recv                  336
#define SYS_recvfrom              337
#define SYS_shutdown              338
#define SYS_setsockopt            339
#define SYS_getsockopt            340
#define SYS_sendmsg               341
#define SYS_recvmsg               342
#define SYS_recvmmsg              343
#define SYS_accept4               344
#define SYS_name_to_handle_at     345
#define SYS_open_by_handle_at     346
#define SYS_clock_adjtime         347
#define SYS_syncfs                348
#define SYS_sendmmsg              349
#define SYS_setns                 350
#define SYS_process_vm_readv      351
#define SYS_process_vm_writev     352
#define SYS_finit_module          353
#define SYS_kcmp                  354
#define SYS_sched_setattr         355
#define SYS_sched_getattr         356
#define SYS_renameat2             357
#define SYS_seccomp               358
#define SYS_getrandom             359
#define SYS_memfd_create          360
#define SYS_bpf                   361
#define SYS_execveat              362
#define SYS_switch_endian         363
#define SYS_userfaultfd           364
#define SYS_membarrier            365
#define SYS_mlock2                378
#define SYS_copy_file_range       379
#define SYS_preadv2               380
#define SYS_pwritev2              381
#define SYS_kexec_file_load       382
#define SYS_statx                 383
#define SYS_pkey_alloc            384
#define SYS_pkey_free             385
#define SYS_pkey_mprotect         386
#define SYS_rseq                  387
#define SYS_io_pgetevents         388
#define SYS_semget                393
#define SYS_semctl                394
#define SYS_shmget                395
#define SYS_shmctl                396
#define SYS_shmat                 397
#define SYS_shmdt                 398
#define SYS_msgget                399
#define SYS_msgsnd                400
#define SYS_msgrcv                401
#define SYS_msgctl                402
#define SYS_clock_gettime64       403
#define SYS_clock_settime64       404
#define SYS_clock_adjtime64       405
#define SYS_clock_getres_time64   406
#define SYS_clock_nanosleep_time64 407
#define SYS_timer_gettime64       408
#define SYS_timer_settime64       409
#define SYS_timerfd_gettime64     410
#define SYS_timerfd_settime64     411
#define SYS_utimensat_time64      412
#define SYS_pselect6_time64       413
#define SYS_ppoll_time64          414
#define SYS_io_pgetevents_time64  416
#define SYS_recvmmsg_time64       417
#define SYS_mq_timedsend_time64   418
#define SYS_mq_timedreceive_time64 419
#define SYS_semtimedop_time64     420
#define SYS_rt_sigtimedwait_time64 421
#define SYS_futex_time64          422
#define SYS_sched_rr_get_interval_time64 423
#define SYS_pidfd_send_signal     424
#define SYS_io_uring_setup        425
#define SYS_io_uring_enter        426
#define SYS_io_uring_register     427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#elif defined(__powerpc64__) /* } { */
#define SYS_restart_syscall          0
#define SYS_exit                     1
#define SYS_fork                     2
#define SYS_read                     3
#define SYS_write                    4
#define SYS_open                     5
#define SYS_close                    6
#define SYS_waitpid                  7
#define SYS_creat                    8
#define SYS_link                     9
#define SYS_unlink                  10
#define SYS_execve                  11
#define SYS_chdir                   12
#define SYS_time                    13
#define SYS_mknod                   14
#define SYS_chmod                   15
#define SYS_lchown                  16
#define SYS_break                   17
#define SYS_oldstat                 18
#define SYS_lseek                   19
#define SYS_getpid                  20
#define SYS_mount                   21
#define SYS_umount                  22
#define SYS_setuid                  23
#define SYS_getuid                  24
#define SYS_stime                   25
#define SYS_ptrace                  26
#define SYS_alarm                   27
#define SYS_oldfstat                28
#define SYS_pause                   29
#define SYS_utime                   30
#define SYS_stty                    31
#define SYS_gtty                    32
#define SYS_access                  33
#define SYS_nice                    34
#define SYS_ftime                   35
#define SYS_sync                    36
#define SYS_kill                    37
#define SYS_rename                  38
#define SYS_mkdir                   39
#define SYS_rmdir                   40
#define SYS_dup                     41
#define SYS_pipe                    42
#define SYS_times                   43
#define SYS_prof                    44
#define SYS_brk                     45
#define SYS_setgid                  46
#define SYS_getgid                  47
#define SYS_signal                  48
#define SYS_geteuid                 49
#define SYS_getegid                 50
#define SYS_acct                    51
#define SYS_umount2                 52
#define SYS_lock                    53
#define SYS_ioctl                   54
#define SYS_fcntl                   55
#define SYS_mpx                     56
#define SYS_setpgid                 57
#define SYS_ulimit                  58
#define SYS_oldolduname             59
#define SYS_umask                   60
#define SYS_chroot                  61
#define SYS_ustat                   62
#define SYS_dup2                    63
#define SYS_getppid                 64
#define SYS_getpgrp                 65
#define SYS_setsid                  66
#define SYS_sigaction               67
#define SYS_sgetmask                68
#define SYS_ssetmask                69
#define SYS_setreuid                70
#define SYS_setregid                71
#define SYS_sigsuspend              72
#define SYS_sigpending              73
#define SYS_sethostname             74
#define SYS_setrlimit               75
#define SYS_getrlimit               76
#define SYS_getrusage               77
#define SYS_gettimeofday            78
#define SYS_settimeofday            79
#define SYS_getgroups               80
#define SYS_setgroups               81
#define SYS_select                  82
#define SYS_symlink                 83
#define SYS_oldlstat                84
#define SYS_readlink                85
#define SYS_uselib                  86
#define SYS_swapon                  87
#define SYS_reboot                  88
#define SYS_readdir                 89
#define SYS_mmap                    90
#define SYS_munmap                  91
#define SYS_truncate                92
#define SYS_ftruncate               93
#define SYS_fchmod                  94
#define SYS_fchown                  95
#define SYS_getpriority             96
#define SYS_setpriority             97
#define SYS_profil                  98
#define SYS_statfs                  99
#define SYS_fstatfs                100
#define SYS_ioperm                 101
#define SYS_socketcall             102
#define SYS_syslog                 103
#define SYS_setitimer              104
#define SYS_getitimer              105
#define SYS_stat                   106
#define SYS_lstat                  107
#define SYS_fstat                  108
#define SYS_olduname               109
#define SYS_iopl                   110
#define SYS_vhangup                111
#define SYS_idle                   112
#define SYS_vm86                   113
#define SYS_wait4                  114
#define SYS_swapoff                115
#define SYS_sysinfo                116
#define SYS_ipc                    117
#define SYS_fsync                  118
#define SYS_sigreturn              119
#define SYS_clone                  120
#define SYS_setdomainname          121
#define SYS_uname                  122
#define SYS_modify_ldt             123
#define SYS_adjtimex               124
#define SYS_mprotect               125
#define SYS_sigprocmask            126
#define SYS_create_module          127
#define SYS_init_module            128
#define SYS_delete_module          129
#define SYS_get_kernel_syms        130
#define SYS_quotactl               131
#define SYS_getpgid                132
#define SYS_fchdir                 133
#define SYS_bdflush                134
#define SYS_sysfs                  135
#define SYS_personality            136
#define SYS_afs_syscall            137
#define SYS_setfsuid               138
#define SYS_setfsgid               139
#define SYS__llseek                140
#define SYS_getdents               141
#define SYS__newselect             142
#define SYS_flock                  143
#define SYS_msync                  144
#define SYS_readv                  145
#define SYS_writev                 146
#define SYS_getsid                 147
#define SYS_fdatasync              148
#define SYS__sysctl                149
#define SYS_mlock                  150
#define SYS_munlock                151
#define SYS_mlockall               152
#define SYS_munlockall             153
#define SYS_sched_setparam         154
#define SYS_sched_getparam         155
#define SYS_sched_setscheduler     156
#define SYS_sched_getscheduler     157
#define SYS_sched_yield            158
#define SYS_sched_get_priority_max 159
#define SYS_sched_get_priority_min 160
#define SYS_sched_rr_get_interval  161
#define SYS_nanosleep              162
#define SYS_mremap                 163
#define SYS_setresuid              164
#define SYS_getresuid              165
#define SYS_query_module           166
#define SYS_poll                   167
#define SYS_nfsservctl             168
#define SYS_setresgid              169
#define SYS_getresgid              170
#define SYS_prctl                  171
#define SYS_rt_sigreturn           172
#define SYS_rt_sigaction           173
#define SYS_rt_sigprocmask         174
#define SYS_rt_sigpending          175
#define SYS_rt_sigtimedwait        176
#define SYS_rt_sigqueueinfo        177
#define SYS_rt_sigsuspend          178
#define SYS_pread64                179
#define SYS_pwrite64               180
#define SYS_chown                  181
#define SYS_getcwd                 182
#define SYS_capget                 183
#define SYS_capset                 184
#define SYS_sigaltstack            185
#define SYS_sendfile               186
#define SYS_getpmsg                187
#define SYS_putpmsg                188
#define SYS_vfork                  189
#define SYS_ugetrlimit             190
#define SYS_readahead              191
#define SYS_pciconfig_read         198
#define SYS_pciconfig_write        199
#define SYS_pciconfig_iobase       200
#define SYS_multiplexer            201
#define SYS_getdents64             202
#define SYS_pivot_root             203
#define SYS_madvise                205
#define SYS_mincore                206
#define SYS_gettid                 207
#define SYS_tkill                  208
#define SYS_setxattr               209
#define SYS_lsetxattr              210
#define SYS_fsetxattr              211
#define SYS_getxattr               212
#define SYS_lgetxattr              213
#define SYS_fgetxattr              214
#define SYS_listxattr              215
#define SYS_llistxattr             216
#define SYS_flistxattr             217
#define SYS_removexattr            218
#define SYS_lremovexattr           219
#define SYS_fremovexattr           220
#define SYS_futex                  221
#define SYS_sched_setaffinity      222
#define SYS_sched_getaffinity      223
#define SYS_tuxcall                225
#define SYS_io_setup               227
#define SYS_io_destroy             228
#define SYS_io_getevents           229
#define SYS_io_submit              230
#define SYS_io_cancel              231
#define SYS_set_tid_address        232
#define SYS_fadvise64              233
#define SYS_exit_group             234
#define SYS_lookup_dcookie         235
#define SYS_epoll_create           236
#define SYS_epoll_ctl              237
#define SYS_epoll_wait             238
#define SYS_remap_file_pages       239
#define SYS_timer_create           240
#define SYS_timer_settime          241
#define SYS_timer_gettime          242
#define SYS_timer_getoverrun       243
#define SYS_timer_delete           244
#define SYS_clock_settime          245
#define SYS_clock_gettime          246
#define SYS_clock_getres           247
#define SYS_clock_nanosleep        248
#define SYS_swapcontext            249
#define SYS_tgkill                 250
#define SYS_utimes                 251
#define SYS_statfs64               252
#define SYS_fstatfs64              253
#define SYS_rtas                   255
#define SYS_sys_debug_setcontext   256
#define SYS_migrate_pages          258
#define SYS_mbind                  259
#define SYS_get_mempolicy          260
#define SYS_set_mempolicy          261
#define SYS_mq_open                262
#define SYS_mq_unlink              263
#define SYS_mq_timedsend           264
#define SYS_mq_timedreceive        265
#define SYS_mq_notify              266
#define SYS_mq_getsetattr          267
#define SYS_kexec_load             268
#define SYS_add_key                269
#define SYS_request_key            270
#define SYS_keyctl                 271
#define SYS_waitid                 272
#define SYS_ioprio_set             273
#define SYS_ioprio_get             274
#define SYS_inotify_init           275
#define SYS_inotify_add_watch      276
#define SYS_inotify_rm_watch       277
#define SYS_spu_run                278
#define SYS_spu_create             279
#define SYS_pselect6               280
#define SYS_ppoll                  281
#define SYS_unshare                282
#define SYS_splice                 283
#define SYS_tee                    284
#define SYS_vmsplice               285
#define SYS_openat                 286
#define SYS_mkdirat                287
#define SYS_mknodat                288
#define SYS_fchownat               289
#define SYS_futimesat              290
#define SYS_newfstatat             291
#define SYS_unlinkat               292
#define SYS_renameat               293
#define SYS_linkat                 294
#define SYS_symlinkat              295
#define SYS_readlinkat             296
#define SYS_fchmodat               297
#define SYS_faccessat              298
#define SYS_get_robust_list        299
#define SYS_set_robust_list        300
#define SYS_move_pages             301
#define SYS_getcpu                 302
#define SYS_epoll_pwait            303
#define SYS_utimensat              304
#define SYS_signalfd               305
#define SYS_timerfd_create         306
#define SYS_eventfd                307
#define SYS_sync_file_range2       308
#define SYS_fallocate              309
#define SYS_subpage_prot           310
#define SYS_timerfd_settime        311
#define SYS_timerfd_gettime        312
#define SYS_signalfd4              313
#define SYS_eventfd2               314
#define SYS_epoll_create1          315
#define SYS_dup3                   316
#define SYS_pipe2                  317
#define SYS_inotify_init1          318
#define SYS_perf_event_open        319
#define SYS_preadv                 320
#define SYS_pwritev                321
#define SYS_rt_tgsigqueueinfo      322
#define SYS_fanotify_init          323
#define SYS_fanotify_mark          324
#define SYS_prlimit64              325
#define SYS_socket                 326
#define SYS_bind                   327
#define SYS_connect                328
#define SYS_listen                 329
#define SYS_accept                 330
#define SYS_getsockname            331
#define SYS_getpeername            332
#define SYS_socketpair             333
#define SYS_send                   334
#define SYS_sendto                 335
#define SYS_recv                   336
#define SYS_recvfrom               337
#define SYS_shutdown               338
#define SYS_setsockopt             339
#define SYS_getsockopt             340
#define SYS_sendmsg                341
#define SYS_recvmsg                342
#define SYS_recvmmsg               343
#define SYS_accept4                344
#define SYS_name_to_handle_at      345
#define SYS_open_by_handle_at      346
#define SYS_clock_adjtime          347
#define SYS_syncfs                 348
#define SYS_sendmmsg               349
#define SYS_setns                  350
#define SYS_process_vm_readv       351
#define SYS_process_vm_writev      352
#define SYS_finit_module           353
#define SYS_kcmp                   354
#define SYS_sched_setattr          355
#define SYS_sched_getattr          356
#define SYS_renameat2              357
#define SYS_seccomp                358
#define SYS_getrandom              359
#define SYS_memfd_create           360
#define SYS_bpf                    361
#define SYS_execveat               362
#define SYS_switch_endian          363
#define SYS_userfaultfd            364
#define SYS_membarrier             365
#define SYS_mlock2                 378
#define SYS_copy_file_range        379
#define SYS_preadv2                380
#define SYS_pwritev2               381
#define SYS_kexec_file_load        382
#define SYS_statx                  383
#define SYS_pkey_alloc             384
#define SYS_pkey_free              385
#define SYS_pkey_mprotect          386
#define SYS_rseq                   387
#define SYS_io_pgetevents          388
#define SYS_semtimedop             392
#define SYS_semget                 393
#define SYS_semctl                 394
#define SYS_shmget                 395
#define SYS_shmctl                 396
#define SYS_shmat                  397
#define SYS_shmdt                  398
#define SYS_msgget                 399
#define SYS_msgsnd                 400
#define SYS_msgrcv                 401
#define SYS_msgctl                 402
#define SYS_pidfd_send_signal      424
#define SYS_io_uring_setup         425
#define SYS_io_uring_enter         426
#define SYS_io_uring_register      427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#elif defined(__riscv) && __riscv_xlen == 64 && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__ /* } { */
#define SYS_io_setup 0
#define SYS_io_destroy 1
#define SYS_io_submit 2
#define SYS_io_cancel 3
#define SYS_io_getevents 4
#define SYS_setxattr 5
#define SYS_lsetxattr 6
#define SYS_fsetxattr 7
#define SYS_getxattr 8
#define SYS_lgetxattr 9
#define SYS_fgetxattr 10
#define SYS_listxattr 11
#define SYS_llistxattr 12
#define SYS_flistxattr 13
#define SYS_removexattr 14
#define SYS_lremovexattr 15
#define SYS_fremovexattr 16
#define SYS_getcwd 17
#define SYS_lookup_dcookie 18
#define SYS_eventfd2 19
#define SYS_epoll_create1 20
#define SYS_epoll_ctl 21
#define SYS_epoll_pwait 22
#define SYS_dup 23
#define SYS_dup3 24
#define SYS_fcntl 25
#define SYS_inotify_init1 26
#define SYS_inotify_add_watch 27
#define SYS_inotify_rm_watch 28
#define SYS_ioctl 29
#define SYS_ioprio_set 30
#define SYS_ioprio_get 31
#define SYS_flock 32
#define SYS_mknodat 33
#define SYS_mkdirat 34
#define SYS_unlinkat 35
#define SYS_symlinkat 36
#define SYS_linkat 37
#define SYS_umount2 39
#define SYS_mount 40
#define SYS_pivot_root 41
#define SYS_nfsservctl 42
#define SYS_statfs 43
#define SYS_fstatfs 44
#define SYS_truncate 45
#define SYS_ftruncate 46
#define SYS_fallocate 47
#define SYS_faccessat 48
#define SYS_chdir 49
#define SYS_fchdir 50
#define SYS_chroot 51
#define SYS_fchmod 52
#define SYS_fchmodat 53
#define SYS_fchownat 54
#define SYS_fchown 55
#define SYS_openat 56
#define SYS_close 57
#define SYS_vhangup 58
#define SYS_pipe2 59
#define SYS_quotactl 60
#define SYS_getdents64 61
#define SYS_lseek 62
#define SYS_read 63
#define SYS_write 64
#define SYS_readv 65
#define SYS_writev 66
#define SYS_pread64 67
#define SYS_pwrite64 68
#define SYS_preadv 69
#define SYS_pwritev 70
#define SYS_sendfile 71
#define SYS_pselect6 72
#define SYS_ppoll 73
#define SYS_signalfd4 74
#define SYS_vmsplice 75
#define SYS_splice 76
#define SYS_tee 77
#define SYS_readlinkat 78
#define SYS_newfstatat 79
#define SYS_fstat 80
#define SYS_sync 81
#define SYS_fsync 82
#define SYS_fdatasync 83
#define SYS_sync_file_range 84
#define SYS_timerfd_create 85
#define SYS_timerfd_settime 86
#define SYS_timerfd_gettime 87
#define SYS_utimensat 88
#define SYS_acct 89
#define SYS_capget 90
#define SYS_capset 91
#define SYS_personality 92
#define SYS_exit 93
#define SYS_exit_group 94
#define SYS_waitid 95
#define SYS_set_tid_address 96
#define SYS_unshare 97
#define SYS_futex 98
#define SYS_set_robust_list 99
#define SYS_get_robust_list 100
#define SYS_nanosleep 101
#define SYS_getitimer 102
#define SYS_setitimer 103
#define SYS_kexec_load 104
#define SYS_init_module 105
#define SYS_delete_module 106
#define SYS_timer_create 107
#define SYS_timer_gettime 108
#define SYS_timer_getoverrun 109
#define SYS_timer_settime 110
#define SYS_timer_delete 111
#define SYS_clock_settime 112
#define SYS_clock_gettime 113
#define SYS_clock_getres 114
#define SYS_clock_nanosleep 115
#define SYS_syslog 116
#define SYS_ptrace 117
#define SYS_sched_setparam 118
#define SYS_sched_setscheduler 119
#define SYS_sched_getscheduler 120
#define SYS_sched_getparam 121
#define SYS_sched_setaffinity 122
#define SYS_sched_getaffinity 123
#define SYS_sched_yield 124
#define SYS_sched_get_priority_max 125
#define SYS_sched_get_priority_min 126
#define SYS_sched_rr_get_interval 127
#define SYS_restart_syscall 128
#define SYS_kill 129
#define SYS_tkill 130
#define SYS_tgkill 131
#define SYS_sigaltstack 132
#define SYS_rt_sigsuspend 133
#define SYS_rt_sigaction 134
#define SYS_rt_sigprocmask 135
#define SYS_rt_sigpending 136
#define SYS_rt_sigtimedwait 137
#define SYS_rt_sigqueueinfo 138
#define SYS_rt_sigreturn 139
#define SYS_setpriority 140
#define SYS_getpriority 141
#define SYS_reboot 142
#define SYS_setregid 143
#define SYS_setgid 144
#define SYS_setreuid 145
#define SYS_setuid 146
#define SYS_setresuid 147
#define SYS_getresuid 148
#define SYS_setresgid 149
#define SYS_getresgid 150
#define SYS_setfsuid 151
#define SYS_setfsgid 152
#define SYS_times 153
#define SYS_setpgid 154
#define SYS_getpgid 155
#define SYS_getsid 156
#define SYS_setsid 157
#define SYS_getgroups 158
#define SYS_setgroups 159
#define SYS_uname 160
#define SYS_sethostname 161
#define SYS_setdomainname 162
#define SYS_getrlimit 163
#define SYS_setrlimit 164
#define SYS_getrusage 165
#define SYS_umask 166
#define SYS_prctl 167
#define SYS_getcpu 168
#define SYS_gettimeofday 169
#define SYS_settimeofday 170
#define SYS_adjtimex 171
#define SYS_getpid 172
#define SYS_getppid 173
#define SYS_getuid 174
#define SYS_geteuid 175
#define SYS_getgid 176
#define SYS_getegid 177
#define SYS_gettid 178
#define SYS_sysinfo 179
#define SYS_mq_open 180
#define SYS_mq_unlink 181
#define SYS_mq_timedsend 182
#define SYS_mq_timedreceive 183
#define SYS_mq_notify 184
#define SYS_mq_getsetattr 185
#define SYS_msgget 186
#define SYS_msgctl 187
#define SYS_msgrcv 188
#define SYS_msgsnd 189
#define SYS_semget 190
#define SYS_semctl 191
#define SYS_semtimedop 192
#define SYS_semop 193
#define SYS_shmget 194
#define SYS_shmctl 195
#define SYS_shmat 196
#define SYS_shmdt 197
#define SYS_socket 198
#define SYS_socketpair 199
#define SYS_bind 200
#define SYS_listen 201
#define SYS_accept 202
#define SYS_connect 203
#define SYS_getsockname 204
#define SYS_getpeername 205
#define SYS_sendto 206
#define SYS_recvfrom 207
#define SYS_setsockopt 208
#define SYS_getsockopt 209
#define SYS_shutdown 210
#define SYS_sendmsg 211
#define SYS_recvmsg 212
#define SYS_readahead 213
#define SYS_brk 214
#define SYS_munmap 215
#define SYS_mremap 216
#define SYS_add_key 217
#define SYS_request_key 218
#define SYS_keyctl 219
#define SYS_clone 220
#define SYS_execve 221
#define SYS_mmap 222
#define SYS_fadvise64 223
#define SYS_swapon 224
#define SYS_swapoff 225
#define SYS_mprotect 226
#define SYS_msync 227
#define SYS_mlock 228
#define SYS_munlock 229
#define SYS_mlockall 230
#define SYS_munlockall 231
#define SYS_mincore 232
#define SYS_madvise 233
#define SYS_remap_file_pages 234
#define SYS_mbind 235
#define SYS_get_mempolicy 236
#define SYS_set_mempolicy 237
#define SYS_migrate_pages 238
#define SYS_move_pages 239
#define SYS_rt_tgsigqueueinfo 240
#define SYS_perf_event_open 241
#define SYS_accept4 242
#define SYS_recvmmsg 243
#define SYS_arch_specific_syscall 244
#define SYS_wait4 260
#define SYS_prlimit64 261
#define SYS_fanotify_init 262
#define SYS_fanotify_mark 263
#define SYS_name_to_handle_at 264
#define SYS_open_by_handle_at 265
#define SYS_clock_adjtime 266
#define SYS_syncfs 267
#define SYS_setns 268
#define SYS_sendmmsg 269
#define SYS_process_vm_readv 270
#define SYS_process_vm_writev 271
#define SYS_kcmp 272
#define SYS_finit_module 273
#define SYS_sched_setattr 274
#define SYS_sched_getattr 275
#define SYS_renameat2 276
#define SYS_seccomp 277
#define SYS_getrandom 278
#define SYS_memfd_create 279
#define SYS_bpf 280
#define SYS_execveat 281
#define SYS_userfaultfd 282
#define SYS_membarrier 283
#define SYS_mlock2 284
#define SYS_copy_file_range 285
#define SYS_preadv2 286
#define SYS_pwritev2 287
#define SYS_pkey_mprotect 288
#define SYS_pkey_alloc 289
#define SYS_pkey_free 290
#define SYS_statx 291
#define SYS_io_pgetevents 292
#define SYS_rseq 293
#define SYS_kexec_file_load 294
#define SYS_pidfd_send_signal 424
#define SYS_io_uring_setup 425
#define SYS_io_uring_enter 426
#define SYS_io_uring_register 427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#define SYS_sysriscv SYS_arch_specific_syscall
#define SYS_riscv_flush_icache (SYS_sysriscv + 15)
#elif defined(__amd64__) /* } { */
#define SYS_read				0
#define SYS_write				1
#define SYS_open				2
#define SYS_close				3
#define SYS_stat				4
#define SYS_fstat				5
#define SYS_lstat				6
#define SYS_poll				7
#define SYS_lseek				8
#define SYS_mmap				9
#define SYS_mprotect			10
#define SYS_munmap				11
#define SYS_brk				12
#define SYS_rt_sigaction		13
#define SYS_rt_sigprocmask		14
#define SYS_rt_sigreturn		15
#define SYS_ioctl				16
#define SYS_pread64			17
#define SYS_pwrite64			18
#define SYS_readv				19
#define SYS_writev				20
#define SYS_access				21
#define SYS_pipe				22
#define SYS_select				23
#define SYS_sched_yield		24
#define SYS_mremap				25
#define SYS_msync				26
#define SYS_mincore			27
#define SYS_madvise			28
#define SYS_shmget				29
#define SYS_shmat				30
#define SYS_shmctl				31
#define SYS_dup				32
#define SYS_dup2				33
#define SYS_pause				34
#define SYS_nanosleep			35
#define SYS_getitimer			36
#define SYS_alarm				37
#define SYS_setitimer			38
#define SYS_getpid				39
#define SYS_sendfile			40
#define SYS_socket				41
#define SYS_connect			42
#define SYS_accept				43
#define SYS_sendto				44
#define SYS_recvfrom			45
#define SYS_sendmsg			46
#define SYS_recvmsg			47
#define SYS_shutdown			48
#define SYS_bind				49
#define SYS_listen				50
#define SYS_getsockname		51
#define SYS_getpeername		52
#define SYS_socketpair			53
#define SYS_setsockopt			54
#define SYS_getsockopt			55
#define SYS_clone				56
#define SYS_fork				57
#define SYS_vfork				58
#define SYS_execve				59
#define SYS_exit				60
#define SYS_wait4				61
#define SYS_kill				62
#define SYS_uname				63
#define SYS_semget				64
#define SYS_semop				65
#define SYS_semctl				66
#define SYS_shmdt				67
#define SYS_msgget				68
#define SYS_msgsnd				69
#define SYS_msgrcv				70
#define SYS_msgctl				71
#define SYS_fcntl				72
#define SYS_flock				73
#define SYS_fsync				74
#define SYS_fdatasync			75
#define SYS_truncate			76
#define SYS_ftruncate			77
#define SYS_getdents			78
#define SYS_getcwd				79
#define SYS_chdir				80
#define SYS_fchdir				81
#define SYS_rename				82
#define SYS_mkdir				83
#define SYS_rmdir				84
#define SYS_creat				85
#define SYS_link				86
#define SYS_unlink				87
#define SYS_symlink			88
#define SYS_readlink			89
#define SYS_chmod				90
#define SYS_fchmod				91
#define SYS_chown				92
#define SYS_fchown				93
#define SYS_lchown				94
#define SYS_umask				95
#define SYS_gettimeofday		96
#define SYS_getrlimit			97
#define SYS_getrusage			98
#define SYS_sysinfo			99
#define SYS_times				100
#define SYS_ptrace				101
#define SYS_getuid				102
#define SYS_syslog				103
#define SYS_getgid				104
#define SYS_setuid				105
#define SYS_setgid				106
#define SYS_geteuid			107
#define SYS_getegid			108
#define SYS_setpgid			109
#define SYS_getppid			110
#define SYS_getpgrp			111
#define SYS_setsid				112
#define SYS_setreuid			113
#define SYS_setregid			114
#define SYS_getgroups			115
#define SYS_setgroups			116
#define SYS_setresuid			117
#define SYS_getresuid			118
#define SYS_setresgid			119
#define SYS_getresgid			120
#define SYS_getpgid			121
#define SYS_setfsuid			122
#define SYS_setfsgid			123
#define SYS_getsid				124
#define SYS_capget				125
#define SYS_capset				126
#define SYS_rt_sigpending		127
#define SYS_rt_sigtimedwait	128
#define SYS_rt_sigqueueinfo	129
#define SYS_rt_sigsuspend		130
#define SYS_sigaltstack		131
#define SYS_utime				132
#define SYS_mknod				133
#define SYS_uselib				134
#define SYS_personality		135
#define SYS_ustat				136
#define SYS_statfs				137
#define SYS_fstatfs			138
#define SYS_sysfs				139
#define SYS_getpriority			140
#define SYS_setpriority			141
#define SYS_sched_setparam			142
#define SYS_sched_getparam			143
#define SYS_sched_setscheduler		144
#define SYS_sched_getscheduler		145
#define SYS_sched_get_priority_max	146
#define SYS_sched_get_priority_min	147
#define SYS_sched_rr_get_interval	148
#define SYS_mlock					149
#define SYS_munlock				150
#define SYS_mlockall				151
#define SYS_munlockall				152
#define SYS_vhangup				153
#define SYS_modify_ldt				154
#define SYS_pivot_root				155
#define SYS__sysctl				156
#define SYS_prctl					157
#define SYS_arch_prctl				158
#define SYS_adjtimex				159
#define SYS_setrlimit				160
#define SYS_chroot					161
#define SYS_sync					162
#define SYS_acct					163
#define SYS_settimeofday			164
#define SYS_mount					165
#define SYS_umount2				166
#define SYS_swapon					167
#define SYS_swapoff				168
#define SYS_reboot					169
#define SYS_sethostname			170
#define SYS_setdomainname			171
#define SYS_iopl					172
#define SYS_ioperm					173
#define SYS_create_module			174
#define SYS_init_module			175
#define SYS_delete_module			176
#define SYS_get_kernel_syms		177
#define SYS_query_module			178
#define SYS_quotactl				179
#define SYS_nfsservctl				180
#define SYS_getpmsg				181
#define SYS_putpmsg				182
#define SYS_afs_syscall			183
#define SYS_tuxcall				184
#define SYS_security				185
#define SYS_gettid					186
#define SYS_readahead				187
#define SYS_setxattr				188
#define SYS_lsetxattr				189
#define SYS_fsetxattr				190
#define SYS_getxattr				191
#define SYS_lgetxattr				192
#define SYS_fgetxattr				193
#define SYS_listxattr				194
#define SYS_llistxattr				195
#define SYS_flistxattr				196
#define SYS_removexattr			197
#define SYS_lremovexattr			198
#define SYS_fremovexattr			199
#define SYS_tkill					200
#define SYS_time					201
#define SYS_futex					202
#define SYS_sched_setaffinity		203
#define SYS_sched_getaffinity		204
#define SYS_set_thread_area		205
#define SYS_io_setup				206
#define SYS_io_destroy				207
#define SYS_io_getevents			208
#define SYS_io_submit				209
#define SYS_io_cancel				210
#define SYS_get_thread_area		211
#define SYS_lookup_dcookie			212
#define SYS_epoll_create			213
#define SYS_epoll_ctl_old			214
#define SYS_epoll_wait_old			215
#define SYS_remap_file_pages		216
#define SYS_getdents64				217
#define SYS_set_tid_address		218
#define SYS_restart_syscall		219
#define SYS_semtimedop				220
#define SYS_fadvise64				221
#define SYS_timer_create			222
#define SYS_timer_settime			223
#define SYS_timer_gettime			224
#define SYS_timer_getoverrun		225
#define SYS_timer_delete			226
#define SYS_clock_settime			227
#define SYS_clock_gettime			228
#define SYS_clock_getres			229
#define SYS_clock_nanosleep		230
#define SYS_exit_group				231
#define SYS_epoll_wait				232
#define SYS_epoll_ctl				233
#define SYS_tgkill					234
#define SYS_utimes					235
#define SYS_vserver				236
#define SYS_mbind					237
#define SYS_set_mempolicy			238
#define SYS_get_mempolicy			239
#define SYS_mq_open				240
#define SYS_mq_unlink				241
#define SYS_mq_timedsend			242
#define SYS_mq_timedreceive		243
#define SYS_mq_notify				244
#define SYS_mq_getsetattr			245
#define SYS_kexec_load				246
#define SYS_waitid					247
#define SYS_add_key				248
#define SYS_request_key			249
#define SYS_keyctl					250
#define SYS_ioprio_set				251
#define SYS_ioprio_get				252
#define SYS_inotify_init			253
#define SYS_inotify_add_watch		254
#define SYS_inotify_rm_watch		255
#define SYS_migrate_pages			256
#define SYS_openat					257
#define SYS_mkdirat				258
#define SYS_mknodat				259
#define SYS_fchownat				260
#define SYS_futimesat				261
#define SYS_newfstatat				262
#define SYS_unlinkat				263
#define SYS_renameat				264
#define SYS_linkat					265
#define SYS_symlinkat				266
#define SYS_readlinkat				267
#define SYS_fchmodat				268
#define SYS_faccessat				269
#define SYS_pselect6				270
#define SYS_ppoll					271
#define SYS_unshare				272
#define SYS_set_robust_list		273
#define SYS_get_robust_list		274
#define SYS_splice					275
#define SYS_tee					276
#define SYS_sync_file_range		277
#define SYS_vmsplice				278
#define SYS_move_pages				279
#define SYS_utimensat				280
#define SYS_epoll_pwait			281
#define SYS_signalfd				282
#define SYS_timerfd_create			283
#define SYS_eventfd				284
#define SYS_fallocate				285
#define SYS_timerfd_settime		286
#define SYS_timerfd_gettime		287
#define SYS_accept4				288
#define SYS_signalfd4				289
#define SYS_eventfd2				290
#define SYS_epoll_create1			291
#define SYS_dup3					292
#define SYS_pipe2					293
#define SYS_inotify_init1			294
#define SYS_preadv					295
#define SYS_pwritev				296
#define SYS_rt_tgsigqueueinfo		297
#define SYS_perf_event_open		298
#define SYS_recvmmsg				299
#define SYS_fanotify_init			300
#define SYS_fanotify_mark			301
#define SYS_prlimit64				302
#define SYS_name_to_handle_at			303
#define SYS_open_by_handle_at			304
#define SYS_clock_adjtime			305
#define SYS_syncfs				306
#define SYS_sendmmsg				307
#define SYS_setns				308
#define SYS_getcpu				309
#define SYS_process_vm_readv			310
#define SYS_process_vm_writev			311
#define SYS_kcmp				312
#define SYS_finit_module			313
#define SYS_sched_setattr			314
#define SYS_sched_getattr			315
#define SYS_renameat2				316
#define SYS_seccomp				317
#define SYS_getrandom				318
#define SYS_memfd_create			319
#define SYS_kexec_file_load			320
#define SYS_bpf				321
#define SYS_execveat				322
#define SYS_userfaultfd			323
#define SYS_membarrier				324
#define SYS_mlock2				325
#define SYS_copy_file_range			326
#define SYS_preadv2				327
#define SYS_pwritev2				328
#define SYS_pkey_mprotect			329
#define SYS_pkey_alloc				330
#define SYS_pkey_free				331
#define SYS_statx				332
#define SYS_io_pgetevents			333
#define SYS_rseq				334
#define SYS_pidfd_send_signal			424
#define SYS_io_uring_setup			425
#define SYS_io_uring_enter			426
#define SYS_io_uring_register			427
#define SYS_open_tree		428
#define SYS_move_mount		429
#define SYS_fsopen		430
#define SYS_fsconfig		431
#define SYS_fsmount		432
#define SYS_fspick		433
#define SYS_pidfd_open		434
#define SYS_clone3		435
#define SYS_close_range	436
#define SYS_openat2		437
#define SYS_pidfd_getfd	438
#define SYS_faccessat2		439
#define SYS_process_madvise	440
#define SYS_epoll_pwait2	441
#define SYS_mount_setattr	442
#define SYS_landlock_create_ruleset	444
#define SYS_landlock_add_rule	445
#define SYS_landlock_restrict_self	446
#define SYS_memfd_secret	447
#define SYS_process_mrelease	448
#define SYS_futex_waitv	449
#define SYS_set_mempolicy_home_node	450
#define SYS_cachestat		451
#define SYS_fchmodat2		452

#else /* } { */
#error "Unknown architecture"
#endif /* } */
